package com.wwb.demo.mapper.mapper;

import com.wwb.demo.entity.Action;

public interface ActionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_action
     *
     * @mbggenerated Thu Dec 06 18:24:16 CST 2018
     */
    int deleteByPrimaryKey(Integer actionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_action
     *
     * @mbggenerated Thu Dec 06 18:24:16 CST 2018
     */
    int insert(Action record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_action
     *
     * @mbggenerated Thu Dec 06 18:24:16 CST 2018
     */
    int insertSelective(Action record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_action
     *
     * @mbggenerated Thu Dec 06 18:24:16 CST 2018
     */
    Action selectByPrimaryKey(Integer actionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_action
     *
     * @mbggenerated Thu Dec 06 18:24:16 CST 2018
     */
    int updateByPrimaryKeySelective(Action record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_action
     *
     * @mbggenerated Thu Dec 06 18:24:16 CST 2018
     */
    int updateByPrimaryKey(Action record);
}