package com.wwb.demo.mapper.mapper;

import com.wwb.demo.entity.AppuserMessage;
import java.util.List;

public interface AppuserMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appuser_message
     *
     * @mbggenerated Wed Dec 05 17:42:22 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appuser_message
     *
     * @mbggenerated Wed Dec 05 17:42:22 CST 2018
     */
    int insert(AppuserMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appuser_message
     *
     * @mbggenerated Wed Dec 05 17:42:22 CST 2018
     */
    AppuserMessage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appuser_message
     *
     * @mbggenerated Wed Dec 05 17:42:22 CST 2018
     */
    List<AppuserMessage> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appuser_message
     *
     * @mbggenerated Wed Dec 05 17:42:22 CST 2018
     */
    int updateByPrimaryKey(AppuserMessage record);
}