package com.wwb.demo.mapper.mapper;

import com.wwb.demo.entity.Person;
import java.util.List;

public interface PersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Wed Dec 05 17:30:20 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Wed Dec 05 17:30:20 CST 2018
     */
    int insert(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Wed Dec 05 17:30:20 CST 2018
     */
    Person selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Wed Dec 05 17:30:20 CST 2018
     */
    List<Person> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Wed Dec 05 17:30:20 CST 2018
     */
    int updateByPrimaryKey(Person record);
}