package com.wwb.demo.entity;

public class AppuserMessage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appuser_message.id
     *
     * @mbggenerated Wed Dec 05 17:42:22 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appuser_message.message
     *
     * @mbggenerated Wed Dec 05 17:42:22 CST 2018
     */
    private String message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appuser_message.sendtime
     *
     * @mbggenerated Wed Dec 05 17:42:22 CST 2018
     */
    private Integer sendtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appuser_message
     *
     * @mbggenerated Wed Dec 05 17:42:22 CST 2018
     */
    public AppuserMessage(Integer id, String message, Integer sendtime) {
        this.id = id;
        this.message = message;
        this.sendtime = sendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appuser_message
     *
     * @mbggenerated Wed Dec 05 17:42:22 CST 2018
     */
    public AppuserMessage() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appuser_message.id
     *
     * @return the value of appuser_message.id
     *
     * @mbggenerated Wed Dec 05 17:42:22 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appuser_message.id
     *
     * @param id the value for appuser_message.id
     *
     * @mbggenerated Wed Dec 05 17:42:22 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appuser_message.message
     *
     * @return the value of appuser_message.message
     *
     * @mbggenerated Wed Dec 05 17:42:22 CST 2018
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appuser_message.message
     *
     * @param message the value for appuser_message.message
     *
     * @mbggenerated Wed Dec 05 17:42:22 CST 2018
     */
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appuser_message.sendtime
     *
     * @return the value of appuser_message.sendtime
     *
     * @mbggenerated Wed Dec 05 17:42:22 CST 2018
     */
    public Integer getSendtime() {
        return sendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appuser_message.sendtime
     *
     * @param sendtime the value for appuser_message.sendtime
     *
     * @mbggenerated Wed Dec 05 17:42:22 CST 2018
     */
    public void setSendtime(Integer sendtime) {
        this.sendtime = sendtime;
    }
}